### ISSUE TITLE
'Used' list pops open on incoming txes (intermittent/hard to reproduce)

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#1042]
@kyuupichan noticed this the other day, and I noticed it today as well. @cculianu says it is not happening on Mac.

Steps to reproduce:
* Have Addresses tab open with a wallet that has used addresses (mine has addresses 0-14 and 16-24 used), with used addresses hidden.
* Receive a tx on an *un*used address, while you have said address selected.
* Observe that the used addresses list gets unhidden.

**Comment by cculianu** [comment]
This doesn't happen on macOS which is why I didn't know about it.  I would have fixed it if it had.

Here is an example -- I kept it selected, sent from 1 wallet to this one and no problem:

<img width="910" alt="screen shot 2018-12-14 at 7 41 29 am" src="https://user-images.githubusercontent.com/266627/49985369-5d376200-ff74-11e8-9817-ee42c64821fe.png">

Must be a Linux thing.  I'll boot up my Linux and try it on there and see if I can figure it out.

Thanks Mark.

**Comment by kyuupichan** [comment]
I run Mac; so it happens on Mac

**Comment by cculianu** [comment]
One more movie with me futzing around trying to reproduce it. If you can figure out exactly what combination of used/unused addresses I need to do it, please do let me know!

https://c3-soft.com/downloads/BitcoinCash/ec_address_bug_cant_reproduce_2.mov

**Comment by cculianu** [comment]
@kyuupichan  @markblundeberg 

I created a PR that I think should at least correctly **enforce** the rule that the previous tree state (expanded/collapsed) cannot be violated by a refresh.  The previous code didn't always guarantee that if the current item moved around in the tree: `setCurrentItem()` would sometimes auto-expand parent tree items.

**Comment by cculianu** [comment]
Please try this PR #1043  and let me know if it addresses the issues you've observed.

**Comment by markblundeberg** [comment]
Yup seems to be fixed now.

**Comment by cculianu** [comment]
Aye.  Awesome! Thanks for checking.

I can conclude the problem was whomever wrote that previous code likely wasn't aware of the (perhaps unintuitive fact) that `setCurrentItem()` on a collapsed `QTreeWidgetItem` parent would cause the parent to expand out as a "convenience"... so their usage wasn't maintaining the invariant they thought they were maintaining.

Good to know it's solved.
