### ISSUE TITLE
Please help me! Electron cash , the transaction was rejected because it is too larger!

### ISSUE THREAD

**Issue by Phamhainam** [Electron-Cash/Electron-Cash#1122]
I want send BCH , I we receive error the transaction was rejected because it is too larger!.
I 
please help me! thank you.
![3](https://user-images.githubusercontent.com/47015752/51717601-56067800-2039-11e9-9dc1-05bad88cf62d.PNG)

**Comment by Phamhainam** [comment]
please help me.

**Comment by imaginaryusername** [comment]
A 330k transaction o_O

Network relay default rule has a 100k/transaction limit, so that's what you ran into there. Instead of sending max for all (which I assume is what you're doing), consolidate in four chunks: Go to the "Coins" tab, select about 1/4th of them by clicking on one end and shift-clicking on the other, then right click -> spend -> max. The resulting transactions should be smaller than 100kb - spend to an intermediate address. Do this four times, then spend to your actual destination from the intermediate address.

**Comment by Phamhainam** [comment]
thank you so much

**Comment by cculianu** [comment]
Hmm. Not a bad idea.  #1125
