### ISSUE TITLE
quero fala senho pol 

### ISSUE THREAD

**Issue by fty48jj19** [Electron-Cash/Electron-Cash#1173]
pol  porque vc esta monitorando endereço errado de mail la no yahoo  vc esta trabalhando com um saite que e meu eu pude costata que vc esta dando suporte  da enpresa para outra pessoa com site motando  olha confisquei hoje  esta tudo errado la  condiçoes precaria nao tem senha endereço errado  como isso aconteçeu registrou algo olha eu ja confirmei  nessa enpresa privacidade e  ja confisquei  lado dos golpista ja vi conta  em aberta com senha de url  senha pessoa desse saite tem uma ip  edentico com meu  olha se esta avendo erro para vc porque vc quer tudo caminha para seu lado certo vou te fala vc vai se visitado pelos provedor  sobre isso  vc tera que da explicaçao dessa situaçao  porque ja registrei  o fato eu volto te fala te mosta onde esta esse saite  q ate senha tenho do saite tudo nome  de tudo que estou fazendo vou tida uma dica 443    118      url  cn-ss-btc.com   esta vc com esse nome pol  olha meu amigo se vc tiver algo de encoveniencia nesse asunto tiver tudo certo  vc sera abesorvido pelo provedor  do saite  https://github.com  e privicidade  do saite da enpresa  se vc tiver envolvimento nisso costa vai ver uma multa para vc  volto fala com vc  sobre aonde vc esta nese episodio  com endereço q nem fuciona nada suport@btc.com  esse endereço nao fuciona  nada nada  seu saite esta fucionado todo vapor  olha  nao vou mas mecionar nada com vc vc sera visitado pelo meu consultores da enpresa ok

**Comment by fty48jj19** [comment]
olha nome talves eu cometi um erro senhor  pool  se for vc se nao for nao vai aver nada  se vc esta em pobremas sera sometido a enpresa ,

**Comment by cculianu** [comment]
Please stop spamming our github with portuguese.  This is an English language project.

I can't tell if you are some bot, some crazy person, or just very confused.

If you continue to post here I will see about getting you banned from this repository.

**Comment by fyookball** [comment]
@fty48jj19 as @cculianu said, we are more than happy to help but we speak only English :)

**Comment by cculianu** [comment]
@fyookball this guy keeps posting here and he even submitted some weird PR. :)

**Comment by fty48jj19** [comment]
ok  eu apenas estou tratando o senhor com educaçao  se o senhor nao tem pobremas neum senho tera sua traquilidade eu enviei para o senhor algo parecido asim porque o senhor colocou uma ameaça um escrito la  nao sou rake nao eu sou o  propetario na empresas tenho aqui 37 milhoes de usuario senho sabe que isso  pois entao por favor o senho esta se setino mordido agora nao sou eu que vou te enportunar nao de maneira alguma agora senhor tem que ter mas postura nao fala dessa maneira eu nao sou maluco nao senhor vc sabe nao tenho so eses provedor nao fica siente disso tenho mas provedores  senhor nao sabe que sabedoria e algo muito enportante olha nao vou enportuna senhor nao  ja mas fareri isso ate porque sou camarada educado senho se conporte nao estou envadino nada do senhor nem pretendo fazer isso nao eu lido com q e meu  eu nao estou mechendo em nada do senho nao  essa ofessa do senhor nao mim afrige nao sabe porque sou acreditado tenho mas provedores acesso a essa empresa bom nao vou fala mas nada meu caro amigo mas olha tenha serteza do que senho faz do que esta certo porque o senhor sabe que tudo na vida a cobraças nao de minha parte mas tenho outra pessoas trabalhando senho pensa q estou agarrado so aqui o senho esta mal acustumado sou pulador da vida nao fico agarrado numa coisa so nao portanto medere sua palavras  senho nao tem educaçao neuma senho nao sabe que isso nao nao voltarei atra do senhor mas nao se nao tem sequencia de nada senho estege livre bom dia para senhor ,

**Comment by cculianu** [comment]
Google translated: "ok I'm just treating you with education if you do not have pobremas neum Ladies will have their tranquility I sent you something asim because you put a threat written it'm not not rake I am propetario the companies have here 37 million Ladies User know this because please then the Ladies this is setino bitten now not I who'll enportunar not in any way now you have to have but posture does not speak that way I'm not crazy not sir u know I have not so onths provider is not siente that have but providers you do not know what wisdom and something very enportante looks will not enportuna you not already but fareri this up because I'm educated comrade Ladies if I'm conporte not envadino anything you do not intend to do it not I read with my q I'm not messing with anything not this Ladies ofessa's not sir me afrige not know because I have believed but providers access to this good company will not speak but nothing my dear friend but look has serteza than Ladies do than this right because you know that everything in life is not for me to cobraças but I have other people working Ladies think q'm hooked so here Ladies this acustumado evil'm jumper of life I'm not hooked on something not only so medere your words do not have education Ladies Ladies neuma not know that no no back atra you but not if they do not have anything sequence Ladies estege free good day to you,"

This looks like gibberish used to beat a Bayesian spam filter.  I can understand some Portuguese and even in Portuguese it looks nonsense.

@fyookball Can you see about banning this guy? I think this qualifies as abuse.  He's already posted like 10 times like this.

**Comment by fty48jj19** [comment]
the whole ploblem that l m  treating him with education but he does not want education he wants someting more he is so sillly that l l know password eveything url  all of him already discoverend here on

**Comment by fty48jj19** [comment]
it is not  pol  not   name  pool
