### ISSUE TITLE
Security: Hardware wallet Trezor seed recovery is not random

### ISSUE THREAD

**Issue by Technologov** [Electron-Cash/Electron-Cash#1191]
When doing seed recovery on Trezor One hardware wallet, it must be random, like
word #7, then word #22, etc...
not #1, #2, #3, else a key-logger can steal the seed and the coins during recovery phase.

https://trezor.io/start website does it correctly.
Electron Cash v3.3.6

-Technologov

**Comment by cculianu** [comment]
Hi, thanks for reporting.  I'll look into this -- I probably have to pull some code from the Electrum codebase.  I lack a trezor so it's doubly hard.

Electrum does it right, correct?

**Comment by Technologov** [comment]
I didn't test Electrum, so I have no idea. But if you're a developer I can sponsor a pair of Trezors for you.

**Comment by cculianu** [comment]
Yes! I am a developer.  Check the commit log on here you'll see my name pop up a lot recently.  I have been very active lately and am very motivated to make these hardware wallet issues go away.

That's the main issue actually -- I lack a hardware device.  Having one in my hands to play with would make the support much better. 

Do you work for Trezor?  I actually just contacted them right now (through their general support site) asking them for a device.

I would love a device sooner rather than later!! If trezor also ends up coming through (I fear it may take them a while to respond if at all) --  I can send you the device they sent me. 

Can you send me one?  

We can take this conversation to private so we can negotiate the details.  Send me an email at "calin.culianu" _AT_ gmail _DOT_ com!

**Comment by cculianu** [comment]
Status Update: I'll fix this very soon!  Also the other extant trezor issues.

**Comment by cculianu** [comment]
I do not believe this is fixable.  The trezorlib is extremely bad and/or buggy and the word order comes from the trezorlib provided by trezor.

What's interesting is their own web-based UI *does* indeed scramble the words.

But if you send a "ScrambedWordsType" seed recovery request to the library -- it still is in sequential order.

I suggest you file an issue here with trezor:  https://github.com/trezor/python-trezor/issues  -- or maybe I'll do so.

Sorry!

**Comment by cculianu** [comment]
Ok so the seed recovery is random in Electron Cash latest git head (we will do a release soon).  On the Trezor One!

On the Model T it's the same as the website -- not random and the trezor people say it doesn't matter as it's secure anyway.

See here:

https://github.com/trezor/python-trezor/issues/373

I'm going to close this issue.
