### ISSUE TITLE
Allow user control of gap limit

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1193]
Electron-cash only watches a certain number of unused addresses (10? 15?) in derivation paths right now - which is fine, but might be undesirable in edge cases (for example, when user generated a lot of new requests without using them, then proceed to restore seed to new wallet). 

It'll be good for the user to be able to set the "gap limit" manually in preference - perhaps in the "transaction" tab.

**Comment by cculianu** [comment]
20 for receiving... 6 for change.

Can add a pref for that. It's always been a pet peeve. I think they left it out because they were afraid nubies would lose funds?

**Comment by cculianu** [comment]
Even better: What about an advanced tool option in the dropdown menu that "scans" for addresses past the gap limit just in case?

**Comment by imaginaryusername** [comment]
>Even better: What about an advanced tool option in the dropdown menu that "scans" for addresses past the gap limit just in case?

Ooh that's neat, "scan more addresses", pops up a dialog, input number and it does its thing - if nothing then pretend nothing happened, if something then new tip of derivation chain! Yes!

...if it's not too much work of course.

**Comment by cculianu** [comment]
Yeah it's easier just to bump the gap limit but.. I would like the dialog box as it's more "nub friendly" in a sense.. and also why raise the gap limit if you don't have to?

**Comment by imaginaryusername** [comment]
True. Actually adjusting gap limit can probably be left to command line like in #1162 for real power users or merchant solutions.

**Comment by cculianu** [comment]
I think #1194 fixes this in a more elegant and generic and user friendly way.

Note it's still possible for power users to modify their gap limit from the console but I think for the average user it's more useful to scan for addresses past gap since that's a more sure-fire way to find addresses.  

Rationale: keeping the gap limit modified creates an ongoing problem of the wallet no longer being easily recoverable unless you remember what gap limit you used.

With this tool you just can scan and not worry.
