### ISSUE TITLE
ux: consider allowing users to pause shuffling while still in "spend shuffled" mode

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1217]
This will keep more users in the shuffle mode and just let them pause when they want to.

Otherwise they have to kick themselves out of shuffle mode and end up spending unshuffled coins when really they just wanted to pause.

**Comment by emergent-reasons** [comment]
Another possibility is to always enable the pause action but move it to the right-click menu for cash shuffle button.

**Comment by fyookball** [comment]
I think there's no good reason to disable the pause button. If we're going to have the button, might as well allow the user to use it; otherwise whats the point.

It's confusing to only allow the button to be enabled if another radio option is selected and how would the user know this is what you have to do?

I don't see a downside to simply allowing it to be enabled and letting the user pause any time. And makes the UI/UX better.

**Comment by cculianu** [comment]
OK, will fix.
