### ISSUE TITLE
fix? ux? switch to spend unshuffled, pause --> coins tab still lists "In queue" for some coins

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1218]

**Comment by emergent-reasons** [comment]
another possibility is to always enable the pause action but move it to the right-click menu for cash shuffle button.

**Comment by fyookball** [comment]
I think there's no good reason to disable the pause button.  If we're going to have the button, might as well allow the user to use it; otherwise whats the point. 

It's confusing to only allow the button to be enabled if another radio option is selected and how would the user know this is what you have to do?

I don't see a downside to simply allowing it to be enabled and letting the user pause any time. And makes the UI/UX better.

**Comment by cculianu** [comment]
Yeah I'll fix it.. after Jonald complained about it too -- definitely will re-enable.
