### ISSUE TITLE
electron cash installation of windows 64 bit

### ISSUE THREAD

**Issue by nikostudent** [Electron-Cash/Electron-Cash#1253]
Hello,
I have a problem with starting an electroncash ver 4.0 on 64 bit windows.
I was unable to find a solution on the Internet for this problem, so I write here.
The platform is windows 7 ultimate 64bit .
Of course, the file is downloaded from the official site electroncash.org
I tried with an older version - it does not go away again.
First I thought it was from the firewall - I use the zone alarm. I de install it but it does not go away again.
The message that comes out to me is:
Elastron cash - 4.0.0 exe Has Stopped working.
I also apply the text from appcrash :
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Electron-Cash-4.0.0.exe
  Application Version:	0.0.0.0
  Application Timestamp:	597f4ad5
  Fault Module Name:	ig7icd32.dll
  Fault Module Version:	10.18.10.5059
  Fault Module Timestamp:	5b75be42
  Exception Code:	c0000005
  Exception Offset:	001363cd
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1026
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by EchterAgo** [comment]
The name of the module `ig7icd32.dll` points to the graphics driver. Did you recently change that? `ig7icd32.dll` is Intel's OpenGL ICD driver.

**Comment by nikostudent** [comment]
Hello,
I downloaded the dll from the Internet and installed as described above. And the program left
Hello,
I downloaded the dll from the Internet and installed as described above. And the program left
Obviously this was the problem.
Thanks for the exact answer.

**Comment by EchterAgo** [comment]
You shouldn't just download a random .dll from the internet. Better to check for an updated Intel Graphics driver, or install an old one. I'm glad it solved the issue for you though.

**Comment by nikostudent** [comment]
I download from 
https://www.dllme.com
is that secure?

**Comment by cculianu** [comment]
That .dll isn't a part of Electron Cash -- why was it being loaded by Electron Cash?

I'm having trouble understanding -- so you installed the DLL then it fixed it? Or you removed the DLL and it fixed it?

Regardless that DLL does not exist if you install electron cash and is not part of Electron Cash.

**Comment by EchterAgo** [comment]
It is not even that the .dll did not exist. The initial report indicates that the .dll was loaded and it crashed inside the .dll. It is loaded by Electron Cash because Qt uses OpenGL to render some UI elements. AFAIK it is better to use ANGLE on Windows, especially with certain graphics drivers with bad OpenGL implementations. ANGLE basically converts OpenGL ES to Direct3D.

**Comment by cculianu** [comment]
Ah I see so that DLL belongs to the guy's video drivers. Gotcha.

We can't really (easily) control what Qt decides to do -- we try to keep the code as platform agnostic as possible (with exceptions) and so if Qt decides to do that .. I feel more comfortable letting it make that decision.  

It probably would be possible to disable opengl altogether in Qt or do other funny business... but, I hesitate to do that.

So I won't try and fix this -- chances are his video drivers' opengl implementation is at fault and I chalk it up to them.

Now if tons of users reported this issue we may work around it.  

But if we band-aid this -- who knows what problems it may cause for others.  It creates a lot of "technical debt" to have to work around platform issues for us in our packaging and disabling OpenGL for the odd user with buggy drivers doesn't seem like a way to go.

As far as that DLL being safe or not.. I have no clue.

**Comment by EchterAgo** [comment]
I am not saying you shouldn't do what Qt decides to do, I am saying Qt defaults to Direct3D on Windows for good reasons, unless it has been deployed or configured wrongly. I had the same issue with my own software.

**Comment by cculianu** [comment]
We just do whatever pyqt does -- it basically installs Qt using pip. *shrugs*

**Comment by EchterAgo** [comment]
I'll try to diagnose this.

**Comment by cculianu** [comment]
ha if you feel like it go for it.

Note in the deterministic.spec in `contrib/build-wine` we may be removing some .DLLs for Qt to make the package "thinner".  I am running around now running errands but it's possible we're removing some stuff that makes Qt fall back to OpenGL.

You can try commenting out this line: 
```
# Strip out parts of Qt that we never use. Reduces binary size by tens of MBs. see #4815
qt_bins2remove=('qt5web', 'qt53d', 'qt5game', 'qt5designer', 'qt5quick',
                'qt5location', 'qt5test', 'qt5xml', r'pyqt5\qt\qml\qtquick')
```

And running a windows build (requires docker -- instructions in `contrib/build-wine`) -- maybe that will solve it by not removing the 3d stuff...

if that's the case Electrum has the same issue (they remove the same bins we do).

**Comment by cculianu** [comment]
Note2: the docker build clones the EC repo to do a deterministic build so to get it to actually point to your repo you have to edit `contrib/base.sh` I think..

**Comment by EchterAgo** [comment]
Angle is `libEGL.dll` and `libGLESV2.dll`, which are included in my PyQt5 on Windows. By default Qt is built with `-opengl dynamic`, which will default to OpenGL 2.0 but fall back on ANGLE if it doesn't like the driver. There is also an optional fallback on `opengl32sw.dll`, which is essentially MESA for Windows and does software rendering, but that is 20MB in size alone. I think we should just make sure to include `libEGL.dll` and `libGLESV2.dll`, which would be an extra 2.4MB. I'll try to get the Windows build going to test it.

**Comment by EchterAgo** [comment]
I created a separate issue for this so we don't spam @nikostudent unnecessarily. Feel free to subscribe to #1255 if you want to follow this issue.
