### ISSUE TITLE
wallet ballance display when hiding CS tx

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#1275]
the balance on the history on the top most tx is not matching the (correct) balance on the bottom left of the wallet, because there were 1 or more subsequent shuffle tx above the last normal tx.

Maybe this is fine because the bottom bar is correct but it might be confusing.  Probably best to leave as is, but what do you think?

**Comment by cculianu** [comment]
I don't believe this to be a bug.  The history list balance up top is only a per-tx balance for whatever is displayed.

Try sorting the history list differently  than the default sorting and see what happens -- now is that a bug too?  (click on one of the columns to change the sorting)

I would argue it isn't a bug.  For everything *shown* in the history list,  it's an accurate per-tx balance. :)

Now, I see what you're saying about it perhaps confusing on first glance: But the fix would be messy.

1. I'd have to add some custom items to the history list such as a  "phantom" tx to show the current balance.. or something?
2. It probably won't matter as this is a power feature that most users don't even use.

My two cents.

**Comment by fyookball** [comment]
> But the fix would be messy.

Agree.  Good to just log the decision then.  Thanks for the consensus.

**Comment by cculianu** [comment]
Just to add to this issue:

We could in the future add an entry:

`xx tx's omitted  - Amount - Balance - Etc..` at the top or whenever there is a "break" due to omitted tx's -- but it's not clear/easy due to the fact that tx's can be sorted in any way (even by "description!") -- so it makes the code messy/hard.

Perhaps we could restrict sorting to only be either ascending or descending by date then, if we wanted to do this.

But I wonder if some users really do like to sort by "Description"... and they would get mad if we took that away?

Food for thought.
