### ISSUE TITLE
Windows: Systray icon is wrong size

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1283]
I get this on Windows:

```
QSystemTrayIcon::showMessage: Wrong icon size (32x32), please add standard one: 40x40
```

Due to display scaling the icon size required isn't 32, but 32*1.25=40. I'll see if I can get it to use an SVG icon.

**Comment by cculianu** [comment]
Well Qt can definitely read SVG.  And I think it should be able to mogrify it using its icon engine and send it to Windows.. so that should work.  

Perhaps unhelpfully that icon is not in SVG in the icons/ folder.  I'll have to ask @fyookball where he got the icon from and/or if he has the original....

**Comment by EchterAgo** [comment]
Hmm, weird, this disappeared even though our new icon doesn't have 40x40.

**Comment by cculianu** [comment]
What do we do?!?! Should we resize the icon to 32x32?

**Comment by cculianu** [comment]
Can we close this now @EchterAgo after your latest icon changes or is this still a relevant issue?

**Comment by EchterAgo** [comment]
This is definitely resolved now
