### ISSUE TITLE
Remove "Shuffled coin spent (frozen for privacy)"

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#1291]
This label is confusing and shouldn't be added.

It's casusing dozens of history items on an address i'm re-using to suddenly have a label where none was desired.

**Comment by cculianu** [comment]
Ok:

1. You are re-using addresses from receiving -- which is normal.  But this happened to a RECEIVING addressyou had a shuffle wallet that shuffled to receiving.  Your wallet pre-dates "shuffle to change".

2. For normal users -- this will only happen on a USED change address.

3. This feature is to protect users from leaking their privacy.

It's a good feature.

The fact that it happened to you on receiving is because you have a wallet that pre-dated the "shuffle to change".  You have an OG wallet.

Normal users will rarely if ever see this.  It's on USED CHANGE.  

This feature is there to tell you not to re-use the address.

**Comment by cculianu** [comment]
Related issue while we were developing: https://github.com/clifordsymack/Electron-Cash/issues/100

**Comment by cculianu** [comment]
Ok so after discussing this with Jonald in telegram, here's what happened:

- Jonald got sent some tx's with equal outputs to a receiving address
- They looked to cashshuffle like shuffled outputs
- Jonald spent said outputs.. cashshuffle thought he had spent private shuffled outputs
- It froze the addresses after spending as per clifordsymack#100

It is what it is.  CashShuffle uses flawed heuristics to decide what is or is not shuffled.

The best we can do here is not freeze receiving addresses ever using the mechanism outlined in https://github.com/clifordsymack/Electron-Cash/issues/100.

I am putting together a commit now to deal with this special case -- and not freeze receiving addresses.
