### ISSUE TITLE
Ledger Nano X Compatibility

### ISSUE THREAD

**Issue by jbertman** [Electron-Cash/Electron-Cash#1368]
Should the Nano X be compatible out of the box? Or are there differences that make an update necessary?

I have been unable to get Electron Cash to recognize the Nano X so far, but I figured it could be related to my system configuration.

I'm currently on Win 10 (Electron Cash 4.0.2), Electron Cash simply doesn't see the Nano X during the scan, but is detected in Ledger Live. I've made sure Ledger Live is closed (have also tried from a fresh restart) and have tried different cables, USB ports, and have removed the device several times. Has anyone been able to get it to work?

![image](https://user-images.githubusercontent.com/4664954/58034377-754b7880-7af4-11e9-87a1-5c78f98b2733.png)

**Comment by cculianu** [comment]
Hi @jbertman  -- would you mind trying this developer release of Electron Cash (4.0.3): https://github.com/Electron-Cash/Electron-Cash/releases -- it may work better since we recently added Nano X support.

Let me know if it works (we plan on releasing this version of Electron Cash very soon but you are free to use it now!)

**Comment by jbertman** [comment]
Working great! Thanks for the prompt support! Closing.

**Comment by cculianu** [comment]
W00t w00t! Glad it's fixed now!
