### ISSUE TITLE
[False Detection]  Windows 4.0.5 EXE - Virus/Trojan Warning

### ISSUE THREAD

**Issue by ConsentDevelopment** [Electron-Cash/Electron-Cash#1420]
Downloaded the latest version of the Electro Cash wallet from the official web site and Bit Defender anti-virus gave the following information -

'The file C:\Users\user-\Downloads\Electron-Cash-4.0.5.exe is infected with Trojan.GenericKD.41343239 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.'

This might be a false positive but I thought it would be good to share with the community.

**Comment by EchterAgo** [comment]
I just reproduced the build for `Electron-Cash-4.0.5.exe` and got the same checksum (7dd97481328132289e832d7f0881c8c4ac0072850d8e5e617ba1ff7d355b8352), so this is a false positive. I've reported this to AV vendors.

**Comment by cculianu** [comment]
Leaving this here just in case someone is reading this so they don't panic:

Electrum suffers from these false detections too: https://www.virustotal.com/gui/file-analysis/NDA5NWFkZDE5ZjQwNzU1ODMzMDM1YjFlMzFhNjU4M2U6MTU1OTU3Mjc4MQ==/detection

**Comment by cculianu** [comment]
This has since been flagged as a false positive.

See attached.

![2019-06-03 19 18 07](https://user-images.githubusercontent.com/266627/58819014-f26c0700-8637-11e9-90e7-c782cfe9d5b9.jpg)
![2019-06-03 19 13 38](https://user-images.githubusercontent.com/266627/58819016-f26c0700-8637-11e9-93f9-a9e1edea98e4.jpg)
