### ISSUE TITLE
Remove bitcoincash: prefix from legacy address QR in receive tab

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1473]
When legacy address mode is used, the QR generator in the receive tab displays a QR that has bitcoincash: prefix, which is unexpected and makes it incompatible with most wallets recognizing legacy addresses.

**Comment by cculianu** [comment]
The payment request really is a URL, though.  And a URL needs a `scheme`, and bitcoin cash's scheme is `bitcoincash:`.   Not really sure what to do there, TBH. 

If they just want the address they can copy the address using the copy button next to it.

Otherwise it is a payment request as a URL.  If you start to fill in info like the description or amount you get parts added to the URL.

Most wallets that support QR should understand that actually.  At least EC does.

So.. not sure what to do there, TBH. 

If they just need an address, copy it with copy button.  That doesn't copy the `bitcoincash:` prefix.

**Comment by imaginaryusername** [comment]
EC-SLP does use simpleledger:xxxx, so it does seem possible to switch to different URL schemes; can legacy simply acquire blank as a scheme?

The usecase is mainly scanning it into mobile wallets.

**Comment by cculianu** [comment]
There is no such thing as blank scheme.  :)  A scheme has to be `something:`


Best we can do is a hackjob where the QR code isn't a URL yet until it has extra parameters (memo, amount, etc) -- so they can scan the QR and it's just a bare address.  But when it does it needs a scheme....

What exactly is the unexpected usecase here? They scan the QR and it has `bitcoincash:1blablalegacy`... and it breaks stuff?

**Comment by cculianu** [comment]
Oh i just read your last line. Ok -- yeah so scanning into mobile.  I guess the hack where it omits the `bitcoincash:` part if it's not a full-on PR yet (no other args besides address) might solve it. And *only* if in legacy mode.

**Comment by imaginaryusername** [comment]
yes, scanning into wallets that don't recognize cashaddr (...I wish they don't exist anymore, ugh) is the main usecase. *Shakes fist* But yeah, legacy mode QR is broken because of that.

**Comment by cculianu** [comment]
Ok, it is done.
