### ISSUE TITLE
Requesting payment from address does not work

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1552]
When I right click a previously used address (in address tab) and request payment from it, the receive tab has the latest unused address in there anyway. Curiously if I request payment from an even futher down (unused) address), that address shows up fine in the Receive box. 

I suspect this is due to Cashshuffle Electron-Cash auto-detecting used addresses and preventing them from showing up in receive tab - which is great for privacy, but does provide an inconsistency in UI. Either allow specific payment request actions to proceed, or remove that right-click option for used addresses altogether. 

I'll personally prefer the latter, as people who really want to reuse addresses can just copy the address itself anyway.

**Comment by cculianu** [comment]
Yeah this is due to conflicting / logical goals that don't arrive at the same conclusion, basically.  The receive tab really doesn't want to re-use addresses as per the CashShuffle changes.

> does provide an inconsistency in UI

I agree.  That's confusing to request payment on a specific address and not get that. Better to not offer it or have it grayed out.

> remove that right-click option for used addresses altogether.

I can have it be grayed out if the action would result in the above-mentioned inconsistency. Only allow it for unused addresses.  This hopefully also underscores how much we hate address re-use. :)

> I'll personally prefer the latter, as people who really want to reuse addresses can just copy the address itself anyway.

Good. Me too. Will fix.
