### ISSUE TITLE
Use emojis to make it easier to verify addresses similar to Telegram key verification method

### ISSUE THREAD

**Issue by damascene** [Electron-Cash/Electron-Cash#1697]
When a user want to send to an address they have to copy and verify it  visually which is  not a very convenient  way because it's just hashes. 

You may consider having emojis next to the "Receiving address" in the "Receive" page similar to the way Telegram key verification method work
![image](https://user-images.githubusercontent.com/411046/69483240-d0f51680-0e35-11ea-845f-b28c7b7fec94.png)

![image](https://user-images.githubusercontent.com/411046/69483215-752a8d80-0e35-11ea-895a-c0b02db12b50.png)
https://core.telegram.org/techfaq#q-how-are-voice-calls-authenticated

**Comment by cculianu** [comment]
Do you know about [CashAccounts](https://www.cashaccount.info/)? It solves just this problem already. Electron Cash supports it.

**Comment by damascene** [comment]
Yes, I know about it, CashAccounts make things easier but registering a cash account for each transaction or using the same address always may not be the optimal thing, it's a feature request.

**Comment by cculianu** [comment]
We aren't likely to ever do this -- so the emoji would just validate the address is not garbage? I'm not sure how useful that is.  You receive that information anyway later.  I'd rather opt for something like highlighting the bad info with red or something clearer.

The telegram scheme actually involves verifying keys and other stuff -- there emojis make sense since you have several possible states: 1. good input, verified, 2. bad/garbage input, not verified, 3. good input, not verified, etc.

Here really it's just simple.  It's like a web form where you didn't fill in your CC # properly.  Either it looks like an address or it doesn't.  The emojis are superfluous.

Also as an aside: emojis don't always work right on all Linux.  if they did I'd be keener on doing it with emojis.

**Comment by cculianu** [comment]
I'm closing this to keep the issue count down.  If someone really wants it to work this way make some noise here and we'll re-open.
