### ISSUE TITLE
daemon mode and JSON-RPC

### ISSUE THREAD

**Issue by FIVIL** [Electron-Cash/Electron-Cash#1798]
Hi, is it possible to use Electron-Cash in daemon mode just like the original electrum wallet for BTC??

I have a working application that works with electrum wallet JSON-RPC perfectly, and now I want to add BCH support to my application, and I was wondering if Electron-Cash has daemon mode and JSON-RPC support as well? and if it does, how different it maybe with the original electrum wallet?

My main concern here is how much change I must do to my code in order to get it to work with Electron-Cash!!!!

**Comment by cculianu** [comment]
Yes, there is a daemon mode.  As for how different it is from current Electrum, I can't answer that with any degree of precision since I haven't kept track of whether or not they have changed their command-line interface.  We have inherited their code for the CLI, and have more or less maintained it in that spirit, adding features we need for BCH.

I suggest you try it and see...

`./electron-cash daemon start`

**Comment by FIVIL** [comment]
Thank you.
