### ISSUE TITLE
potential (and actual) problems with uncompressed keys from Old_KeyStore

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1859]
I recently had failures making flipstarter pledges using a wallet that still uses seed type 'old'.

Jonathan Silverblood analysed the problem in flipstarter backend and found that 

> The underying issue is that we have assumed that we will only get compressed public keys, and your situation has resulted in your wallet making uncompressed keys.

I dug in a little bit and found that even a freshly created wallet using that old seed of mine would still result in the same issue. So most like the Old_KeyStore implementation is.

Now I understand that uncompressed keys are perfectly fine per se, but I've been thinking about the implications (excuse my naiveté, I don't fully grasp the mechanics at hand):

 * maybe the use of uncompressed keys (if not widespread, which is probably the case) can have some implications regarding privacy (both in general but also in regard to shuffle/fusion maybe?) Do those uncompressed keys appear in transactions on-chain at all?
 * If flipstarter runs into problems, what about other things, especially "smart-contract-type" solutions involving complex scripts and such. Could those be affected in the sense that the scripts expect compressed keys at some point and fail (maybe with dramatic consequences)?

**Could that Old_KeyStore implementation be changed to use compressed keys at all?**

Maybe I'm being paranoid and there's obvious workarounds for the problem of course. Just want to avoid potential trouble down the road... Let me quote Jonathan on one solutions he proposed:

> We update the flipstarter backend to accept uncompressed keys and use the pledge as it stands right now. (likely to work fine, but if it doesn't **can cause fullfillment of campaign to fail later,**

Can anyone shed some light as to how likely/severe potential problems in defi stuff could be down the road?

**Comment by molecular** [comment]
for reference flipstarter issue about this: https://gitlab.com/flipstarter/frontend/-/issues/73

**Comment by cculianu** [comment]
Ok to clarify a few points:

- uncompressed keys are not insecure in any way shape or form. They are just a less compact encoding of the same thing (a point on an EC curve).

- on-chain addresses derived from uncompressed private keys have exactly the same security guarantees that compressed keys do.

- Smart contract scripts shouldn't have this limitation.    I suspect this is just a bug or oversight in flipstarter's plugin code, if anything.

> Could that Old_KeyStore implementation be changed to use compressed keys at all?

Sadly, no.  It's set in stone.  It uses a deterministic algorithm cooked up long ago before BIP44 and all the other stuff was devised.  It cannot be changed.  If you have an old seed, and you want to see your funds -- you are stuck.  The reason why it can't be changed is that an uncompressed key changed to compressed will yield a different address (different hash160) on-chain and so you won't be able to see your balance with the way Electrum server work.  

> Maybe I'm being paranoid and there's obvious workarounds for the problem of course. 

There is no problem on our end.  The problem is that the implementers of Flipstarter, bless their hearts, don't support uncompressed keys.  Uncompressed keys exist though.  They are a reality.  it probably would be worth it for them to support them.

> Can anyone shed some light as to how likely/severe potential problems in defi stuff could be down the road?

Again, this is an issue with flipstarter.  Uncompressed keys are not insecure or bad.  Please understand that.  The whole tone of your message makes it sound like uncompressed keys are bad or insecure.  They are not.

**Comment by molecular** [comment]
Okay.

I understand it's an issue with flipstarter. I just figured if this was an easy change, life could be made easier for contract devs. We can see this can be a pitful with the flipstarter example at hand.

Thanks for looking into this.
