### ISSUE TITLE
UnboundLocalError: local variable 'tx' referenced before assignment

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2078]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/ehsan/workspace/SLP/Electron-Cash-SLP/gui/qt/main_window.py", line 2549, in do_send
    fee = tx.get_fee()

UnboundLocalError: local variable 'tx' referenced before assignment
```

Reporter
------------

This issue was reported by 3 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.6.1  | 3.7.3 (default, Jul 25 2020, 13:03:44)  [GCC 8.3.0] | Linux-4.19.0-12-amd64-x86_64-with-debian-10.6 | slp_standard | en_US | 
| 3.6.6  | 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_PH | 
| 3.6.6  | 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_PH | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by gasull** [comment]
This is actually Bitcoin Cash SLP edition, so it should have been reported on [its GitHub](https://github.com/simpleledger/Electron-Cash-SLP/issues).

But 3.6.1 is an old release, since the [latest one is 3.6.5](https://github.com/simpleledger/Electron-Cash-SLP/releases/tag/3.6.5).

Also, I'm not sure the version reported is correct, since [line 2549 of `gui/qt/main_window.py` in release 3.6.1](https://github.com/simpleledger/Electron-Cash-SLP/blob/d92da8b213ba84e9470e7b0da9453d6651f99efa/gui/qt/main_window.py#L2549) doesn't contain the instruction
```Python
fee = tx.get_fee()
```

I think this issue should be closed.

**Comment by gasull** [comment]
Since this is a bot reporting a crash, could the logic of the automatic reporting be broken?

**Comment by mhsmith** [comment]
I maintain the bot, and I'm not aware of any bugs in the version number or line number reporting. But it depends on the app to report its own version number, so maybe that wasn't properly updated, or maybe this is someone running an intermediate unreleased version.
