### ISSUE TITLE
Windows 10 thinks it's a virus

### ISSUE THREAD

**Issue by aeronhibby** [Electron-Cash/Electron-Cash#2080]
I've been unable to download the latest release because Windows keeps deleting it and giving a warning:
![virus1](https://user-images.githubusercontent.com/9427396/100554795-ec1a1380-324b-11eb-8ab5-a1db61fa9550.jpg)
![virus2](https://user-images.githubusercontent.com/9427396/100554798-f63c1200-324b-11eb-911e-88d5d8240748.jpg)

**Comment by sykoe** [comment]
same problem, different virus detected 
![image](https://user-images.githubusercontent.com/953678/101486509-0dba7f80-395d-11eb-902a-893df5cd4290.png)

**Comment by EchterAgo** [comment]
Quote from the Electrum site:

> **Notes for Windows users**
> Electrum binaries are often flagged by various anti-virus software. There is nothing we can do about it, so please stop reporting that to us. Anti-virus software uses heuristics in order to determine if a program is malware, and that often results in false positives. If you trust the developers of the project, you can verify the GPG signature of Electrum binaries, and safely ignore any anti-virus warnings. If you do not trust the developers of the project, you should build the binaries yourself, or run the software from source. Finally, if you are really concerned about malware, you should not use an operating system that relies on anti-virus software.

So verify the signatures. The binaries are built by 3 people independently and they match, so you can be very sure there is not a Virus inside the file you downloaded if you verify the signatures.

If you update your signature files, you will also find that most of the time the false detection is already gone. If not, and you have verified the signature, report it as a false positive to Microsoft here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by cculianu** [comment]
Thanks @EchterAgo for responding to this often-cited lament from users.

@aeronhibby Thanks for reporting but yes, unfortunately we cannot do anything about this.  We have taken steps to make our binary a bit less likely to not get flagged but sadly it still gets flagged off and on.  This may be because other malware exists that pretends to be Electron Cash for phishing, or because in general malware programs don't like crypto.  Or who knows what.  We have struggled with this for 1.5 years already and at this point will just have to declare that we cannot ever fix this 100%.  Sorry.  Closing issue.
