### ISSUE TITLE
Upgrading Win7 EC from 4.2.3 to 4.2.4 behavior broken

### ISSUE THREAD

**Issue by jkister** [Electron-Cash/Electron-Cash#2295]
EC 4.2.4-setup asks if i want to uninstall 4.2.3 before installing 4.2.4.

i click 'yes'

EC 4.2.4 then installs.  after installation it asks if i want to uninstall EC.  
if you click yes, it deletes 4.2.4.

seems the order of operations is wrong.

**Comment by cculianu** [comment]
Pinging @EchterAgo ... he updated the installer for 4.2.4 I believe.

**Comment by EchterAgo** [comment]
The uninstaller runs when you click yes, but the installer does not wait for its completion, causing it to be in the background until the installation process finishes. This is fixed by https://github.com/Electron-Cash/Electron-Cash/pull/2184 which is not included in 4.2.4 but will be in the next version.

**Comment by cculianu** [comment]
Ah, thanks for clearing that up @EchterAgo :)
