### ISSUE TITLE
Explain practical CashShuffle / CashFusion usage

### ISSUE THREAD

**Issue by xanoni** [Electron-Cash/Electron-Cash#2312]
Hi, couldn't find any easily digestible documentation to answer the below questions, maybe someone can help.

1) Is CashFusion meant to replace CashShuffle?
2) If yes, why is CashShuffle still included in Electron Cash?
3) What happens if both are turned on at the same time (which is something that the wallet allows)?
4) If only CashFusion is used, how can I easily see the anonymity set of each UTXO?
5) How can I specify when Electron Cash should stop CashFusion? (E.g., how can I specify a certain anonymity set when the coinjoins should stop?)

Thank you!

**Comment by emergent-reasons** [comment]
I just saw this issue sitting here after a long time. It should probably be clarified to avoid confusion. For now, let me provide some answers here so at least it is documented.

> 1) Is CashFusion meant to replace CashShuffle?

Yes

> 2) If yes, why is CashShuffle still included in Electron Cash?

I'm not sure but probably because when it was released, there was still a question of whether it was really a clearly better solution. The opinion on that has trended toward "yes, it's a clearly superior solution". So likely, shuffle is just there because it takes effort to remove it.

> 3) What happens if both are turned on at the same time (which is something that the wallet allows)?

Probably they will compete to freeze coins and end up having problems. Also possible it just works. However more practically speaking, since liquidity has moved to fusion, it will probably be impossible to have a meaningful volume of shuffles.

> 4) If only CashFusion is used, how can I easily see the anonymity set of each UTXO?

I don't think there is any statistical measure built in. How would you want to see it presented? Maybe that can be setup as an issue for future improvements.

> 5) How can I specify when Electron Cash should stop CashFusion? (E.g., how can I specify a certain anonymity set when the coinjoins should stop?)

In the beginning, you couldn't. Now there is a setting to stop after all coins have been fused at least X times.

**Comment by xanoni** [comment]
Thank you. I haven't used the latest version, but any anonymity measure would be better than none. Not sure if you can see something as simple as # of fusion cycles by now.

**Comment by emergent-reasons** [comment]
> Not sure if you can see something as simple as # of fusion cycles by now.

Yes you can :+1:

**Comment by xanoni** [comment]
I guess that's good enough of a proxy for now, thank you. Could maybe be made more granular (compare to the anonset metric that e.g. Wasabi is showing). But that's more of a nice to have, given fusion is comparatively cheap (so you just do a few extra rounds).
