### ISSUE TITLE
Android - Unable to set GAP LIMIT  via Console and GUI

### ISSUE THREAD

**Issue by konnjuta** [Electron-Cash/Electron-Cash#2378]
There's no GUI option to set gap limit.
Attempted change_gap_limit() and changegaplimit() on the console CLI but it doesn't seem to be working.

Electron-Cash/android/app/src/main/python/electroncash_gui/android/console.py 

Doesn't seem to have declare the gap limit function either.

Feature yet to be implemented?

**Comment by rmwb** [comment]
wallet.change_gap_limit() seems to work for me.

**Comment by konnjuta** [comment]
> wallet.change_gap_limit() seems to work for me.

On Android? really?
I can get  that CLI command working on desktop but not on Android it gives:

File "<console>", Line1, <module> NameError: name 'wallet' is not defined.

**Comment by mhsmith** [comment]
On Android, try `c.wallet.change_gap_limit`.

Explanation: on the desktop there is one window per wallet, so the lifetime of the console is the same as the lifetime of the wallet. But the Android app has a single, persistent console, which you can access even when no wallet is open. So instead of `wallet` being a top-level variable, it's wrapped in the `Commands` object, which is assigned to the variable `c`.

**Comment by konnjuta** [comment]
> On Android, try `c.wallet.change_gap_limit`.

Thanks for sharing that I need to specify different context ie "c vs wallet". Learning something new.
However, still getting issue. Error is now:

File "< console >", Line1, in < module > AttributeError:  'AndroidCommands' object has no attribute 'change_gap_limit'

**Comment by mhsmith** [comment]
Did you enter `c.change_gap_limit`? I said `c.wallet.change_gap_limit`.

**Comment by konnjuta** [comment]
> Did you enter `c.change_gap_limit`? I said `c.wallet.change_gap_limit`.

My bad. Made the error as you described. Running c.wallet.change_gap_limit(1000) returns true.
