### ISSUE TITLE
CashFusion fails with "stopping due to inactivity" message

### ISSUE THREAD

**Issue by carbongreat13** [Electron-Cash/Electron-Cash#2496]
I have been running Electron Cash since October 27 with Fusion rounds set to 3 and it has only been done twice at most. Some coins have only been fused once.
Why is CashFusion taking so unusually long?
I usually use VPN, but even if I disable it, I still get the same error.

**Comment by imaginaryusername** [comment]
"stopping due to inactivity" is simply a message that indicates the pool resetting after waiting for participants for a while, it's completely normal. In case you don't know, _all_ mixing protocols require sufficient participants to be present in order to mix, fusion is no exception.

Simply wait longer unless you get a glut of other more specific messages.
