### ISSUE TITLE
libsecp256k1 0.3.1 support?

### ISSUE THREAD

**Issue by reliant8307** [Electron-Cash/Electron-Cash#2596]
Currently Electron-Cash requires an old libsecp256k1. Is there any plan to upgrade this requirement to a newer version like libsecp256k1 0.3.1?

Thanks.

**Comment by ar-jan** [comment]
Yes please, this will help for packages built by distributions with shared libraries, since electrum v4.4.1 moved to using libsecp256k1 v0.3.1 (libsecp256k1.so.2).

**Comment by cculianu** [comment]
The thing is, you can use any version but Electron Cash requires the Bitcoin Cash version of the library (since it is not identical to Core's version). That's the real trouble here.

So I am presuming you are referring to the Core version that you would like Electron Cash to play nice with -- you CAN use the Core version, and it will speed-up ECDSA sigs.. but then for Schnorr sigs it won't work at all since Core's Schnorr stuff differs from Bitcoin Cash's.

So either way you can't just use the Electrum lib 100% with Electron Cash and have it speed up everything. You CAN use it but it won't help with doing fast Schnorr -- and fast Schnorr is needed for CashFusion to work...

**Comment by ar-jan** [comment]
Ah, that's good to know. I hadn't really looked at the differences, I'm updating Electrum for Void Linux, and currently Void's Electrum and Electron Crash are both using a https://github.com/libbitcoin/secp256k1 (which is very outdated). So I thought I'd switch both to https://github.com/bitcoin-core/secp256k1 v0.3.1 instead.

If I understand correctly, that version would also work for Electron Cash (with the caveats you mention)?

But it looks like Electron Cash should rather be packaged using https://github.com/Bitcoin-ABC/secp256k1.

**Comment by cculianu** [comment]
> If I understand correctly, that version would also work for Electron Cash (with the caveats you mention)?

Yes, it will work, and normal ECDSA signing is sped up by the use of that version, but Schnorr sigs (and thus CashFusion) would not be able to be sped up and will be slow python-only fallback implementation. CashFusion requires fast schnorr so CashFusion wouldn't work.

> But it looks like Electron Cash should rather be packaged using https://github.com/Bitcoin-ABC/secp256k1.

Yes correct, that would work 100%. We have an outdated copy of that repo here too: https://github.com/Electron-Cash/secp256k1.

**Comment by reliant8307** [comment]
> The thing is, you can use any version but Electron Cash requires the Bitcoin Cash version of the library (since it is not identical to Core's version). That's the real trouble here.

I didn't know about that. So I'm closing this issue, since there's no point in using the Core version. Thank you!
