### ISSUE TITLE
Transaction fee is not shown for all incoming transactions

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#811]
When right click -> details, fees (as well as fee per byte) is shown for all outgoing transactions, but not incoming transactions. As fee can be calculated by input - output, fee for incoming tx should be retrievable as well.

**Comment by cculianu** [comment]
I'll take a look at this.  Got an address on a wallet I can do "watching only" so i can reproduce?

**Comment by cculianu** [comment]
Did a little digging and saw that the "amounts" for the inputs to a TX always there in the wallet code.  The Mark Lundeberg told me that basically to know the amounts for inputs, you have to download the previous tx -- and Electron Cash doesn't do this as a performance optimization.

So yes -- we can add this if you really really want. 

I'll leave this issue open and file it under "enhancement".  

I'm on your side on this -- I, too, would like to see that info in the Tx Dialog rather than "unknown".

**Comment by imaginaryusername** [comment]
Ah, I see why the fee was not displayed, thanks. I'll love to see this happen, and the impact to performance can be minimal if it only retrieves previous-tx when the box is opened... probably. Thanks for checking!

**Comment by cculianu** [comment]
This is a very good suggestion.  Grab the results on-demand as the user opens the wallet, and then update the dialog when the results come in (if it's still open), and "remember" the results.

This way we don't grab all the data -- only data that we know users might be interested in because they physically went out of their wait to get a tx-detail screen on a particular transaction.  I like it!

I'll think about doing this.  I actually really want to do it.  The only question is how onerous it would be code-wise.  

Thanks for the suggestion and I will keep this issue open and keep this in mind.

**Comment by cculianu** [comment]
This has finally been addressed if using the "download input data" feature. FINALLY!

https://github.com/Electron-Cash/Electron-Cash/releases/tag/4.0.6-dev1
