### ISSUE TITLE
Transfer from Gemini to Electron never showed

### ISSUE THREAD

**Issue by rabooze** [Electron-Cash/Electron-Cash#894]
New user to all of this. I am trying to transfer some BCH from Gemini account into my default Electron wallet. Both transactions just show pending after 9 days in Electron. Blockchain search shows both transactions with over 1k confirmations. Help!

**Comment by fyookball** [comment]
you're sure is a BCH explorer not BTC right?

Try connecting to to new server in the network tab (click the green circle on bottom right to open network tab).  Failing that, please show me a screenshot.

**Comment by cculianu** [comment]
@rabooze I think you may want to install [Electrum](https://github.com/spesmilo/electrum).

Gemini definitely doesn't offer BCH trading yet, as far as I know.

You want to get a BTC client, @rabooze.  Electron Cash is for BCH.

**Comment by cculianu** [comment]
PS: @rabooze do NOT delete your electron wallet.  You will need it to get a recovery seed that you will use with Electrum to generate a BTC wallet from the same electron cash seed.

**Comment by imaginaryusername** [comment]
@cculianu I think Gemini does have withdraw only: https://twitter.com/GeminiTrust/status/916676395576758273

So @rabooze if you indeed withdrew BCH and not BTC and downloaded the correct Electron-Cash (directly from electroncash.org, right?), then the only thing i can think of is you might have somehow connected to a "straggling" server who failed to update last time we did an upgrade. 

Follow @fyookball 's advice, click the green light bottom right and see if you're on a server that contains "jns" in it, that was the one straggling server i've seen from a while back. If it is, right click and use any other server on the list that has a longer chain.

**Comment by cculianu** [comment]
Oh .. I stand corrected!  (Not sure how they offer withdrawals without trading -- or did they finally turn BCH trading on?)

Ok well it could be any number of things.. including a straggling server.

@rabooze If privacy is not your concern -- you could always tell us the txid that way we can be sure the tx exists on the BCH network.  But it's not required and not even recommended.  Just if you happen to not care about privacy, it might help clear up communication here (I'm still suspicious that perhaps you may be doing BTC erroneously).

**Comment by rabooze** [comment]
Yes, I think I may have mistyped. It think it is BTC which is probably the conflict with Electron, as I understand it. I am away from my computer now but can confirm with you all later when I get back. I really appreciate your help! It’s not a ton of $ because I knew I was learning so I didn’t want to risk some accidental transfer of thousands. I will let you all know what I uncover

**Comment by rabooze** [comment]
I looked and it is a BTC transfer, not BCH. That seems to be the issue. Once I install Electrum, how do I cancel my current transaction or redirect to Electrum? Thanks again for all your help!!

**Comment by imaginaryusername** [comment]
BCH has replay protection, so you don't need to "cancel" any protection; it probably doesn't actually exist on the BCH network. Just import private keys into Electrum and you should see the incoming tx.

**Comment by cculianu** [comment]
@rabooze Ok, so you have to get Electrum to "see" the same addresses that Electron Cash "sees".  You likely grabbed an address from Electron Cash and pasted it into Gemini as the "withdraw to" address, right?

You have two options:

1. Open up Electron Cash and click on the "seed" icon on the bottom.  It's the second-to-last icon in this image:

<img width="171" alt="screen shot 2018-10-11 at 8 15 17 pm" src="https://user-images.githubusercontent.com/266627/46821797-6a787a80-cd92-11e8-9860-a170394537d8.png">

If you don't see  a seed icon there, don't worry.  You can try exporting the private key.  But the seed method is easier.

2. If you DO see a seed icon, copy down the seed phrase you see in the window that pops up.  

3. Open up Electrum and pick File -> New/Restore and say 'restore from seed' when the wizards opens up.  Paste or type in that seed phrase you copied down.

If the above doesn't work because you don't see a seed icon, let me know and I'll show you how to export private keys.

**Comment by rabooze** [comment]
This worked. Thanks so much!

**Comment by cculianu** [comment]
Awesome! I'm glad it was no big deal in the end and you got your funds. :)
