### ISSUE TITLE
Bug in bitcoin.py?

### ISSUE THREAD

**Issue by cculianu** [Electron-Cash/Electron-Cash#933]
#932 just got reported by the crash reporter.

Here is the relevant code (this is from ios newwallet.py):

```
def _ImportItemify(item : str) -> ImportItem:
    item = item.strip()
    info = None
    typ = 0
    if Address.is_valid(item):
        typ = 1
        info = Address.from_string(item)
        item = item.split(':')[-1]
    elif bitcoin.is_private_key(item):
        typ = 2
        try:
            info = PublicKey.from_WIF_privkey(item).address
        except ValueError:
            # Not an address, not a PK
            info, typ = None, 0
    return ImportItem(item, typ, info)
```

The ~`try...catch`~`try...except` clause at the end is new (to handle the exception).

Notice how I ask the library "is_private_key"?  And it returns true.  Yet later on `PublicKey.from_WIF_privkey(item).address` raises an exception.

Any reasonable library shouldn't answer "yes" to a question to which the answer is "no". 

Or... `PublicKey.from_WIF_privkey` has bugs.  Can't tell which.

Thoughts?

**Comment by rt121212121** [comment]
Thoughts are that this hides a problem and makes it a) impossible to track down b) adds technical debt.

I suggest we let it continue to happen, and if we make any changes we do so in a way that raises an alternate exception with extra context, and then iterate on that letting it continue to happen until the problem goes away.

A problem with the crash reporting is that it pressures us to fix things with only superficial information. Better to take a iterative approach rather than slapping a band-aid over something and ignoring it IMO.

**Comment by cculianu** [comment]
I *do* however agree that we should fix the root of this problem and was keeping "the problem" alive by creating a separate explicit issue for it, with more background info.

**Comment by cculianu** [comment]
Yep that’s it. Pretty sure. I’ll fix. Thanks @kyuupichan

**Comment by cculianu** [comment]
Ok well never mind. Bitcoin.py was ok, if lacking in comments.

Closing issue. All is right.
