### ISSUE TITLE
100% CPU usage / frozen while syncing heavily-used address

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#979]
The following wallet (for the eatBCH public donation address) has some serious issues syncing. 

[eatbchwallet.txt](https://github.com/Electron-Cash/Electron-Cash/files/2613591/eatbchwallet.txt)

The wallet file above is empty (being created offline) and watches a single address: [pp8skudq3x5hzw8ew7vzsw8tn4k8wxsqsv0lt0mf3g](https://blockchair.com/bitcoin-cash/address/pp8skudq3x5hzw8ew7vzsw8tn4k8wxsqsv0lt0mf3g). Once you open it up it will start syncing then soon it reaches 100% CPU and freezes electron cash. This frozen/high CPU state persists indefinitely, as far as I can tell.

Noteworthy points about this address:

* 2-of-3 multisignature P2SH
* 9500 transactions
* **9500 unspent outputs**

Probably related to #817 but this is a more severe example. (ping @rt121212121 @cculianu @imaginaryusername)

**Comment by rt121212121** [comment]
My understanding is that the core problem is the code providing the data for  the UI (history list), which gets and builds history.  We deal with this by reducing the frequency the UI gets updated, thanks to Calin's code rate limiting updates.  Electrum had rewritten the UI to be a little more flexible (IIRC from when I try and recall about this), and that would possibly be able to handle more entries.  But it looked like complicated to update.

**Comment by cculianu** [comment]
Yep @rt121212121 and @markblundeberg  -- the GUI update code ends up calling  `wallet.py get_history` https://github.com/Electron-Cash/Electron-Cash/blob/5872a67d3ea3bf80b14a64f16aa2ca9411234b97/lib/wallet.py#L831.

It looks suspiciously for-loopey and possibly quadratic O(n^2) at first glance. 

I would start there.  

#### Approaches: 

1. We could profile it and see if we can make it more efficient without it losing functionality.
2. We could also see about it caching some of the data it recomputes each time it's called -- with special attention on an associated mechanism to invalidate/expire the cache so the cached data -- so that the addition of a cache doesn't produce new bugs (eg when switching chains or if there's a reorg we would want to expire the cache, etc).
3. If the above doesn't prove to be enough, call it increasingly less frequently if some threshold is met -- some sort of exponential growth and decay formula parameterized by call frequency can be used (a great use for the mathematical constant **`e`** and natural logarithms! Weee!).

**Comment by jhoenicke** [comment]
One problem is SPV.run() in verifier.py goes through all unverified items over and over again just to check if they were already requested.  It shouldn't probably do this while requested_merkle is not empty.  Or unverified items need to be moved to another list, while they are worked on.

**Comment by cculianu** [comment]
@jhoenicke wow I didn't even look at that code. Thanks for the tip.

**Comment by jhoenicke** [comment]
Now it is hanging in utxo_list.py in `on_update`

**Comment by cculianu** [comment]
So it's both the GUI updates and the verifier. :(

Here is a screenshot of me re-starting ec with the wallet .. It's been spewing forth these messages for 10 mins now. GUI totally frozen.

<img width="809" alt="screen shot 2018-11-26 at 2 14 30 am" src="https://user-images.githubusercontent.com/266627/48986752-5a89df80-f121-11e8-8c9e-a7dd6de954de.png">

**Comment by jhoenicke** [comment]
for some reason moving it one line up, breaks the selection.

**Comment by cculianu** [comment]
This change you suggested is making it much faster @jhoenicke !! Good find!!!

I'm pushed a commit up now that moves it 1 line up. It really makes a difference.

**Comment by cculianu** [comment]
@jhoenicke you sure it breaks it? Nothing in my knowledge of how Qt works would indicate that would be the case. I'm also testing it right now and it's working fine.

**Comment by SomberNight** [comment]
Re verifier; try https://github.com/spesmilo/electrum/commit/1b95cced5d9251919b98f2a116bc79caaaf9f8bc

Again, someone should keep an eye on upstream stuff.

**Comment by cculianu** [comment]
@jhoenicke ok I pushed another commit up that calls setSelected() only if it needs to be set to true. This appears faster.

@SomberNight I will see about adapting this commit to our code.  At this point you guys are using this async/future stuff and we need to do that at some point so.. we've been bad about keeping up with upstream. :)

**Comment by markblundeberg** [comment]
Checked out 433113b6884c9d03d45e90af1eb915709402e727 and it loaded the 30 MB synced wallet (which I had prepared using daemon) immediately. HUGE change since on the previous master it just freezes.

**Comment by cculianu** [comment]
Awesome. Thanks for trying int @markblundeberg .  Yeah on macOS the GUI was dealing with the situation better.  I think the bug was basically `setSelected` being called for each item (default is false anyway), even if not selected, would trigger a repaint.  Interesting that on macOS the slowdown wasn't as noticeable (I guess macOS WindowServer is pretty good about collating multiple calls).

But on Linux that `repaint()` spam was what did it.

@SomberNight this fixup you suggested is making a huge difference in terms of the time it's taking to synch this wallet.  It went down from 20 mins on my system to less than 10. THANK YOU!

**Comment by cculianu** [comment]
Lots of recent commits have made this much more manageable.  We now rate limit a lot of the GUI redraw code.  Closing to keep issue count down.
