### ISSUE TITLE
transferring SV and ABC

### ISSUE THREAD

**Issue by mykedjonz** [Electron-Cash/Electron-Cash#982]
hi,
I forgot to add BCHabc to electron cash, and I went to the SV chain and sent the SV coins to my SV wallet, and when I check the ABC chain, the same transaction appears.
does it mean I won't get the ABC coins?

**Comment by cculianu** [comment]
Your transaction may have gotten replayed on the ABC chain even though you issued it on the SV chain.  This is because the SV nodes and ABC nodes are talking to each other and they are relaying each others' transactions.

This is why everybody was obsessed lately with "splitting their coins".

So I take it you didn't split your coins and this is what happened?

Where did the ABC coins end up? Is it an address you control?  Or did you send them to an exchange?

If the ABC coins ended up on an address you control (or an honest exchange) you will get them back.

If it's your address -- you can easily get them.  Let me know more and perhaps I can help.

**Comment by mykedjonz** [comment]
thank you for the prompt reply.I sent the SV to Coinsquare.coinsquare says that SV is pending, however no news about ABC.I forgot to split it myself since I never done this before.




On Monday, November 26, 2018, 3:31 PM, Calin Culianu <notifications@github.com> wrote:


Your transaction may have gotten replayed on the ABC chain even though you issued it on the SV chain. This is because the SV nodes and ABC nodes are talking to each other and they are relaying each others' transactions.

This is why everybody was obsessed lately with "splitting their coins".

So I take it you didn't split your coins and this is what happened?

Where did the ABC coins end up? Is it an address you control? Or did you send them to an exchange?

If the ABC coins ended up on an address you control (or an honest exchange) you will get them back.

If it's your address -- you can easily get them. Let me know more and perhaps I can help.

**Comment by cculianu** [comment]
I've never heard of coinsquare but it appears to be an exchange.  It's going to be a little bit complicated because basically you sent the same funds to the same address on 2 different chains.  It's at an address they control.  

First, before you do anything else: **Do NOT send any more funds either on SV or on ABC chains**.  You need to split your funds.  Here is a little reddit guide I put together for doing so: 

https://www.reddit.com/r/btc/comments/9xmh2n/psa_how_to_split_your_coins_with_electron_cash/

But until you split your coins (if you have any coins left) -- do not continue to transact on the network.  Doing so is dangerous and could lead to lost funds.

Next, contact coinsquare and tell them that your SV transaction to them was replayed on the ABC chain and that you want them to refund you those funds.

Hopefully they can get the funds to you.  It's a customer support nightmare for them too -- but with any luck you will eventually get your funds back.  

The funds went to an address they control so -- they should technically be able to do it, even if it's labor intensive for them (depending on how their systems are configured).

Good luck man!  I'm sorry this happened.  

BSV has announced they will implement replay protection in the future (perhaps a bit late) -- this fork drama has had its victims.

**Comment by mykedjonz** [comment]
Hi Calin.please help with this issue, I transferred yesterday 1 abc and 1 sv.both wallets say Synchronizing, been 24hwhat does it mean?




On Monday, November 26, 2018, 3:31 PM, Calin Culianu <notifications@github.com> wrote:


Your transaction may have gotten replayed on the ABC chain even though you issued it on the SV chain. This is because the SV nodes and ABC nodes are talking to each other and they are relaying each others' transactions.

This is why everybody was obsessed lately with "splitting their coins".

So I take it you didn't split your coins and this is what happened?

Where did the ABC coins end up? Is it an address you control? Or did you send them to an exchange?

If the ABC coins ended up on an address you control (or an honest exchange) you will get them back.

If it's your address -- you can easily get them. Let me know more and perhaps I can help.
